sudo: required

services: 
  - docker


before_install:
  - docker build -t modusoperandi/docker-react -f Dockerfile.dev .

script:
  - docker run modusoperandi/docker-react npm run test -- --coverage